# Day 3 
 

In [3]:
import numpy as np

In [6]:
count = np.arange(1,13)
b  = count.reshape(3,4)
a = np.arange(5,17)
c = a.reshape(4,3)
print(b)
print(count.reshape(3,4))



[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [23]:
new_count = count + 5
print(new_count)

[ 6  7  8  9 10 11 12 13 14 15 16 17]


In [25]:
print(b*c)

[[  5  12  21  32]
 [ 45  60  77  96]
 [117 140 165 192]]


In [36]:
d = np.dot(b,c)
print(d)

[[110 120 130]
 [262 288 314]
 [414 456 498]]


In [8]:

np.dot(b, b.T)

array([[ 30,  70, 110],
       [ 70, 174, 278],
       [110, 278, 446]])

In [11]:
a = np.arange(1,13).reshape(3,4)
b = np.arange(1,5)
result = a + b
print(result)

[[ 2  4  6  8]
 [ 6  8 10 12]
 [10 12 14 16]]


In [13]:
a = np.ones((2,3))
b = np.ones((3,))
c = np.dot(a,b)
print(c)

[3. 3.]
