# DAY 4 

In [2]:
import numpy as np


In [17]:
marks = np.array([[78,45,79],[88,99,81],[38,89,92]])
print(marks)

[[78 45 79]
 [88 99 81]
 [38 89 92]]


In [7]:
morethan85 = marks > 85
print(marks[morethan85])

[88 99 89 92]


In [9]:
count = np.sum(marks > 80)
print(count)

6


In [18]:
lowermarks = marks.copy()
lowerthan70 = lowermarks <70
lowermarks[lowerthan70] = 50
print(lowermarks)

[[78 50 79]
 [88 99 81]
 [50 89 92]]
