In [2]:
import numpy as np

In [3]:
marks = np.array([[85, 78, 92],
 [70, 88, 80],
 [90, 95, 85]])

In [4]:
print(marks[1])

[70 88 80]


In [20]:
print(marks[:,1])

[78 88 95]


In [14]:
print(marks.max())

95


In [18]:
print(marks.shape)
print(marks.flatten())

(3, 3)
[85 78 92 70 88 80 90 95 85]
